# Generated by Django 4.1.2 on 2022-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=123, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cc',
            field=models.CharField(max_length=19),
        ),
    ]
