# Generated by Django 4.1.2 on 2022-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0002_rename_password_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
    ]
